export const ACTION_TYPES = {
    // Controller login and Registration
    CNTRL_LOGIN: "CNTRL_LOGIN",
    CNTRL_REGISTRATION: "CNTRL_REGISTRATION",

    RX_SET_AUTH_BOOL: 'RX_SET_AUTH_BOOL',

    // Delete Task

    CNTRL_DELETE_TASK: "CNTRL_DELETE_TASK",

    
    // Tasks

    CNTRL_ADD_TASK: 'CNTRL_ADD_TASK', //

    // GET
    CNTRL_GET_ALL_TASK: 'CNTRL_GET_ALL_TASK',  //
    RX_GET_ALL_TASK: 'RX_GET_ALL_TASK',
    RX_GET_ALL_TASK_PENDING: 'RX_GET_ALL_TASK_PENDING', //
    RX_GET_ALL_TASK_DONE: 'RX_GET_ALL_TASK_DONE', //

    // LogOut
    CNTRL_LOGOUT: "CNTRL_LOGOUT",


    // PUT
    CNTRL_PUT_ALL_TASK: 'CNTRL_PUT_ALL_TASK',  //
    RX_PUT_ALL_TASK: 'RX_PUT_ALL_TASK',
    RX_PUT_ALL_TASK_PENDING: 'RX_PUT_ALL_TASK_PENDING', //
    RX_PUT_ALL_TASK_DONE: 'RX_PUT_ALL_TASK_DONE', //

    // PUT Task
    CNTRL_PUT_TASK: 'CNTRL_PUT_TASK',  //
    RX_PUT_TASK: 'RX_PUT_TASK',
    RX_PUT_TASK_PENDING: 'RX_PUT_TASK_PENDING', //
    RX_PUT_TASK_DONE: 'RX_PUT_TASK_DONE', //

    // GET Task By ID
    CNTRL_GET_TASK_BY_ID: 'CNTRL_GET_TASK_BY_ID', //


    RX_SELECT_TASK_BY_ID: 'RX_GET_TASK_BY_ID',
}